rabbitmq:
 image: rabbitmq:3-management
 ports:
  - "5672:5672"
  - "15672:15672"

discovery:
 image: discovery-server
 ports:
  - "8761:8761"

auth:
 image: auth-server
 ports:
  - "9999:9999"

mysql-price:
 image: mysql
 environment:
  MYSQL_DATABASE: pricerevenue
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: admin
  MYSQL_PASSWORD: root
 ports:
  - "3306:3306"

price:
 image: price-service
 links:
  - discovery
  - mysql-price

revenue:
 image: revenue-service
 links:
  - discovery
  - mysql-price

price-composite:
 image: price-composite
 links:
  - discovery
  - rabbitmq

revenue-composite:
 image: revenue-composite
 links:
  - discovery
  - rabbitmq

priceapi:
 image: price-api-service
 links:
  - auth
  - discovery
  - rabbitmq

turbine:
 image: turbine
 links:
  - discovery

monitor:
 image: monitor-dashboard
 ports:
  - "7979:7979"
 links:
  - priceapi
  - price-composite
  - revenue-composite
  - turbine

edge:
 image: edge-server
 ports:
  - "443:8765"
 links:
  - discovery
  - priceapi