rabbitmq:
 image: rabbitmq:3-management
 ports:
  - "5672:5672"
  - "15672:15672"

discovery:
 image: artifactory.mars.haw-hamburg.de:5002/discovery-server
 ports:
  - "8761:8761"

auth:
 image: artifactory.mars.haw-hamburg.de:5002/auth-server
 ports:
  - "9999:9999"

mysql-price:
 image: mysql
 environment:
  MYSQL_DATABASE: pricerevenue
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: admin
  MYSQL_PASSWORD: root
 ports:
  - "3306:3306"

price:
 image: artifactory.mars.haw-hamburg.de:5002/price-service-pricing-blue
 links:
  - discovery
  - mysql-price

revenue:
 image: artifactory.mars.haw-hamburg.de:5002/revenue-service-pricing-blue
 links:
  - discovery
  - mysql-price

price-composite:
 image: artifactory.mars.haw-hamburg.de:5002/price-composite-pricing-blue
 links:
  - discovery
  - rabbitmq

revenue-composite:
 image: artifactory.mars.haw-hamburg.de:5002/revenue-composite-pricing-blue
 links:
  - discovery
  - rabbitmq

priceapi:
 image: artifactory.mars.haw-hamburg.de:5002/price-api-service-pricing-blue
 links:
  - auth
  - discovery
  - rabbitmq

turbine:
 image: artifactory.mars.haw-hamburg.de:5002/turbine
 links:
  - discovery

monitor:
 image: artifactory.mars.haw-hamburg.de:5002/monitor-dashboard
 ports:
  - "7979:7979"
 links:
  - priceapi
  - price-composite
  - revenue-composite
  - turbine

edge:
 image: artifactory.mars.haw-hamburg.de:5002/edge-server
 ports:
  - "443:8765"
 links:
  - discovery
  - priceapi